In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [4]:
df=pd.read_csv('IMDB-Movie-Dataset(2023-1951).csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2199 entries, 0 to 2198
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  2199 non-null   int64
 1   movie_id    2199 non-null   object
 2   movie_name  2199 non-null   object
 3   year        2134 non-null   object
 4   genre       2199 non-null   object
 5   overview    2199 non-null   object
 6   director    2199 non-null   object
 7   cast        2199 non-null   object
dtypes: int64(1), object(7)
memory usage: 137.6+ KB

In [5]:
df.head(5)

,Unnamed: 0,movie_id,movie_name,year,genre,overview,director,cast
0,0,tt15354916,Jawan,2023,"Action, Thriller",A high-octane action thriller which outlines t...,Atlee,"Shah Rukh Khan, Nayanthara, Vijay Sethupathi, ..."
1,1,tt15748830,Jaane Jaan,2023,"Crime, Drama, Mystery",A single mother and her daughter who commit a ...,Sujoy Ghosh,"Kareena Kapoor, Jaideep Ahlawat, Vijay Varma, ..."
2,2,tt11663228,Jailer,2023,"Action, Comedy, Crime",A retired jailer goes on a manhunt to find his...,Nelson Dilipkumar,"Rajinikanth, Mohanlal, Shivarajkumar, Jackie S..."
3,3,tt14993250,Rocky Aur Rani Kii Prem Kahaani,2023,"Comedy, Drama, Family",Flamboyant Punjabi Rocky and intellectual Beng...,Karan Johar,"Ranveer Singh, Alia Bhatt, Dharmendra, Shabana..."
4,4,tt15732324,OMG 2,2023,"Comedy, Drama",An unhappy civilian asks the court to mandate ...,Amit Rai,"Pankaj Tripathi, Akshay Kumar, Yami Gautam, Pa..."

In [7]:
#drop unnamed col it not useful
df.drop(df.columns[df.columns.str.contains('unnamed', case=False)], axis=1, inplace=True)

In [35]:
df.head(4)

,movie_id,movie_name,year,overview,director,cast,,Action,Adventure,Animation,...,History,Horror,Music,Musical,Mystery,Romance,Sci-Fi,Sport,Thriller,War
0,15354916,Jawan,2023,A high-octane action thriller which outlines t...,Atlee,"Shah Rukh Khan, Nayanthara, Vijay Sethupathi, ...",0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
1,15748830,Jaane Jaan,2023,A single mother and her daughter who commit a ...,Sujoy Ghosh,"Kareena Kapoor, Jaideep Ahlawat, Vijay Varma, ...",0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
2,11663228,Jailer,2023,A retired jailer goes on a manhunt to find his...,Nelson Dilipkumar,"Rajinikanth, Mohanlal, Shivarajkumar, Jackie S...",0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3,14993250,Rocky Aur Rani Kii Prem Kahaani,2023,Flamboyant Punjabi Rocky and intellectual Beng...,Karan Johar,"Ranveer Singh, Alia Bhatt, Dharmendra, Shabana...",0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [10]:
df['movie_id']=df['movie_id'].str.replace('tt','')

In [31]:
from sklearn.preprocessing import MultiLabelBinarizer

mlb = MultiLabelBinarizer()

genre_encoded = pd.DataFrame(
    mlb.fit_transform(df['genre']),
    columns=mlb.classes_,
    index=df.index
)

df = pd.concat([df, genre_encoded], axis=1)

In [34]:
df.drop('genre',axis=1,inplace=True)

In [29]:
#now genre will issur as it contains mulitple genre
df['genre'] = df['genre'].apply(lambda x: [i.strip() for i in x.split(',')])

In [12]:
from sklearn.feature_extraction.text import TfidfVectorizer
corpus = ["This is the first document.", "This document is the second document."]
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(corpus)
print(vectorizer.get_feature_names_out())
print(X.toarray())

['document' 'first' 'is' 'second' 'the' 'this']
[[0.4090901  0.57496187 0.4090901  0.         0.4090901  0.4090901 ]
 [0.66758217 0.         0.33379109 0.46913173 0.33379109 0.33379109]]

In [36]:
df.columns

Index(['movie_id', 'movie_name', 'year', 'overview', 'director', 'cast', '',
       'Action', 'Adventure', 'Animation', 'Biography', 'Comedy', 'Crime',
       'Drama', 'Family', 'Fantasy', 'History', 'Horror', 'Music', 'Musical',
       'Mystery', 'Romance', 'Sci-Fi', 'Sport', 'Thriller', 'War'],
      dtype='object')

In [38]:
df_clustering=df.drop(['year', 'overview', 'director', 'cast'],axis=1)

In [39]:
df_clustering.head(4)

,movie_id,movie_name,,Action,Adventure,Animation,Biography,Comedy,Crime,Drama,...,History,Horror,Music,Musical,Mystery,Romance,Sci-Fi,Sport,Thriller,War
0,15354916,Jawan,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,15748830,Jaane Jaan,0,0,0,0,0,0,1,1,...,0,0,0,0,1,0,0,0,0,0
2,11663228,Jailer,0,1,0,0,0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
3,14993250,Rocky Aur Rani Kii Prem Kahaani,0,0,0,0,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0