In [7]:
import pandas as pd
import numpy as np

In [21]:
df=pd.read_csv('ai_models_performance.csv')

In [22]:
df.head()

,Model,Context Window,Creator,Intelligence Index,Price (Blended USD/1M Tokens),Speed(median token/s),Latency (First Answer Chunk /s)
0,GPT-5.2 (xhigh),400k,OpenAI,51,$4.81,100,44.29
1,Claude Opus 4.5,200k,Anthropic,49,$10.00,79,1.70
2,Gemini 3 Pro Preview (high),1m,Google,48,$4.50,128,32.19
3,GPT-5.1 (high),400k,OpenAI,47,$3.44,127,26.50
4,Gemini 3 Flash,1m,Google,46,$1.13,224,11.62

In [24]:
grp_by_creator=df.groupby('Creator')
grp_by_creator

In [14]:
d=np.random.randint(1,10,size=(4,6))
x=pd.DataFrame(d,columns=['A','B','C','D','E','F'],index=['X','Y','Z','W'])
x

   A  B  C  D  E  F
X  2  4  2  8  3  5
Y  4  1  6  7  6  2
Z  6  4  7  6  5  8
W  5  5  2  9  7  9

In [15]:
x['AB']=x['A']*x['B']
x

   A  B  C  D  E  F  AB
X  2  4  2  8  3  5   8
Y  4  1  6  7  6  2   4
Z  6  4  7  6  5  8  24
W  5  5  2  9  7  9  25

In [16]:
row_sum=x.sum(axis=1)
col_sum=x.sum(axis=0)
print(row_sum)
print(col_sum)

X    32
Y    30
Z    60
W    62
dtype: int64
A     17
B     14
C     17
D     30
E     21
F     24
AB    61
dtype: int64